name: Deploy React Website

on:
  push:
    branches:
      - react-intro
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies and Build
        run: sudo apt-get install -y lftp
      - name: Deploy to cPanel React Subdomain
        run: |
          lftp -d -c "
          set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }};
          mirror -R --verbose --only-newer --parallel=10 ./ /react-dev;
          bye;
          "
